"""create initial tables

Revision ID: 202ba9fab637
Revises: d1d214908152
Create Date: 2025-09-18 09:08:12.342552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '202ba9fab637'
down_revision = 'd1d214908152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_session_id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.String(length=256), nullable=True),
    sa.Column('company_size', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('core_products_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unique_selling_proposition', sa.String(length=1024), nullable=True),
    sa.Column('target_audience', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_info_analysis_session_id'), 'company_info', ['analysis_session_id'], unique=False)
    op.create_table('contact_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_session_id', sa.UUID(), nullable=False),
    sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('social', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_info_analysis_session_id'), 'contact_info', ['analysis_session_id'], unique=False)
    op.create_table('extracted_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_session_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=1024), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_answers_analysis_session_id'), 'extracted_answers', ['analysis_session_id'], unique=False)
    op.create_table('page_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_session_id', sa.UUID(), nullable=False),
    sa.Column('final_url', sa.String(length=1024), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('meta_description', sa.String(length=1024), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('main_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_snapshots_analysis_session_id'), 'page_snapshots', ['analysis_session_id'], unique=False)
    op.create_table('qa_exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_session_id', sa.UUID(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('agent_response', sa.Text(), nullable=False),
    sa.Column('context_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_exchanges_analysis_session_id'), 'qa_exchanges', ['analysis_session_id'], unique=False)
    op.create_index(op.f('ix_analysis_sessions_url'), 'analysis_sessions', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_sessions_url'), table_name='analysis_sessions')
    op.drop_index(op.f('ix_qa_exchanges_analysis_session_id'), table_name='qa_exchanges')
    op.drop_table('qa_exchanges')
    op.drop_index(op.f('ix_page_snapshots_analysis_session_id'), table_name='page_snapshots')
    op.drop_table('page_snapshots')
    op.drop_index(op.f('ix_extracted_answers_analysis_session_id'), table_name='extracted_answers')
    op.drop_table('extracted_answers')
    op.drop_index(op.f('ix_contact_info_analysis_session_id'), table_name='contact_info')
    op.drop_table('contact_info')
    op.drop_index(op.f('ix_company_info_analysis_session_id'), table_name='company_info')
    op.drop_table('company_info')
    # ### end Alembic commands ###
