"""create analysis_sessions

Revision ID: d1d214908152
Revises: 
Create Date: 2025-09-17 18:02:04.702769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1d214908152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ai_provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('sentiment', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    


def downgrade() -> None:
    op.drop_table('analysis_sessions')
    # ### end Alembic commands ###
